apiVersion: v1
kind: Service
metadata:
  name: map-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: map-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
