apiVersion: v1
kind: ServiceAccount
metadata:
  name: map-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::863676520919:role/mapweather-map-api-irsa-role
