replicaCount: 2

image:
  repository: 863676520919.dkr.ecr.ap-northeast-2.amazonaws.com/map-weather
  tag: weather-api-1.0
  pullPolicy: Always

containerPort: 3001

service:
  type: ClusterIP
  port: 80

env:
  - name: AWS_REGION
    value: ap-northeast-2
  - name: AWS_STS_REGIONAL_ENDPOINTS
    value: regional
  - name: WEATHER_PARAM_NAME
    value: /dev/weather-api/openweather-api-key

serviceAccount:
  name: weather-api-sa
  annotations:
    eks.amazonaws.com/role-arn: ""  # Helm deploy 시 GitHub Actions에서 채움
