apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      serviceAccountName: weather-api-sa
      containers:
        - name: weather-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3