apiVersion: v1
kind: Service
metadata:
  name: weather-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: weather-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
