name: Deploy Frontend to S3

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Generate alb-config.json
        run: |
          ALB_DNS=$(aws ssm get-parameter --name "/mapweather/alb-dns" --query 'Parameter.Value' --output text)
          echo "{\"albUrl\": \"http://$ALB_DNS\"}" > ./frontend/build/alb-config.json
          cat ./frontend/build/alb-config.json

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://map-weather-seraching --delete
